// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assemble_coefs
NumericVector assemble_coefs(NumericVector pqx, NumericVector rqx, NumericVector pqy, NumericVector rqy, NumericVector C, String method, NumericVector XBeta_diffusion, NumericVector XBeta_advection_1, NumericVector XBeta_advection_2, NumericVector XBeta_mortality, int nele, NumericVector node_x, NumericVector node_y, NumericVector el_1);
RcppExport SEXP _Jsmm_assemble_coefs(SEXP pqxSEXP, SEXP rqxSEXP, SEXP pqySEXP, SEXP rqySEXP, SEXP CSEXP, SEXP methodSEXP, SEXP XBeta_diffusionSEXP, SEXP XBeta_advection_1SEXP, SEXP XBeta_advection_2SEXP, SEXP XBeta_mortalitySEXP, SEXP neleSEXP, SEXP node_xSEXP, SEXP node_ySEXP, SEXP el_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pqx(pqxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rqx(rqxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pqy(pqySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rqy(rqySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type XBeta_diffusion(XBeta_diffusionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type XBeta_advection_1(XBeta_advection_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type XBeta_advection_2(XBeta_advection_2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type XBeta_mortality(XBeta_mortalitySEXP);
    Rcpp::traits::input_parameter< int >::type nele(neleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type node_x(node_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type node_y(node_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type el_1(el_1SEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_coefs(pqx, rqx, pqy, rqy, C, method, XBeta_diffusion, XBeta_advection_1, XBeta_advection_2, XBeta_mortality, nele, node_x, node_y, el_1));
    return rcpp_result_gen;
END_RCPP
}
// assemble_integral
NumericVector assemble_integral(NumericVector k_v, NumericVector detB, int nnod, int ns, int nele, NumericVector el_v);
RcppExport SEXP _Jsmm_assemble_integral(SEXP k_vSEXP, SEXP detBSEXP, SEXP nnodSEXP, SEXP nsSEXP, SEXP neleSEXP, SEXP el_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k_v(k_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type detB(detBSEXP);
    Rcpp::traits::input_parameter< int >::type nnod(nnodSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nele(neleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type el_v(el_vSEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_integral(k_v, detB, nnod, ns, nele, el_v));
    return rcpp_result_gen;
END_RCPP
}
// assemble_mass
NumericVector assemble_mass(NumericVector k, NumericVector ML, NumericVector detB, NumericVector vals, int nele, NumericVector xPos);
RcppExport SEXP _Jsmm_assemble_mass(SEXP kSEXP, SEXP MLSEXP, SEXP detBSEXP, SEXP valsSEXP, SEXP neleSEXP, SEXP xPosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ML(MLSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type detB(detBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nele(neleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xPos(xPosSEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_mass(k, ML, detB, vals, nele, xPos));
    return rcpp_result_gen;
END_RCPP
}
// assemble_stiffness
NumericVector assemble_stiffness(NumericVector k, NumericVector ML, NumericVector detB, NumericVector vals, int nele, NumericVector xPos, NumericVector coef, NumericVector Bj, NumericVector C, NumericVector node_x, NumericVector node_y, NumericVector el_1, NumericVector pre11_01, NumericVector pre11_02, NumericVector pre11_03, NumericVector pre11_AC, NumericVector pre22_01, NumericVector pre22_02, NumericVector pre22_03, NumericVector pre22_BC, NumericVector preB1_01, NumericVector preB1_02, NumericVector preB1_03, NumericVector preB2_01, NumericVector preB2_02, NumericVector preB2_03, NumericVector Kxpp, NumericVector Kypp, NumericVector Kpp);
RcppExport SEXP _Jsmm_assemble_stiffness(SEXP kSEXP, SEXP MLSEXP, SEXP detBSEXP, SEXP valsSEXP, SEXP neleSEXP, SEXP xPosSEXP, SEXP coefSEXP, SEXP BjSEXP, SEXP CSEXP, SEXP node_xSEXP, SEXP node_ySEXP, SEXP el_1SEXP, SEXP pre11_01SEXP, SEXP pre11_02SEXP, SEXP pre11_03SEXP, SEXP pre11_ACSEXP, SEXP pre22_01SEXP, SEXP pre22_02SEXP, SEXP pre22_03SEXP, SEXP pre22_BCSEXP, SEXP preB1_01SEXP, SEXP preB1_02SEXP, SEXP preB1_03SEXP, SEXP preB2_01SEXP, SEXP preB2_02SEXP, SEXP preB2_03SEXP, SEXP KxppSEXP, SEXP KyppSEXP, SEXP KppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ML(MLSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type detB(detBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nele(neleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xPos(xPosSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Bj(BjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type node_x(node_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type node_y(node_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type el_1(el_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre11_01(pre11_01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre11_02(pre11_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre11_03(pre11_03SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre11_AC(pre11_ACSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre22_01(pre22_01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre22_02(pre22_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre22_03(pre22_03SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pre22_BC(pre22_BCSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preB1_01(preB1_01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preB1_02(preB1_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preB1_03(preB1_03SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preB2_01(preB2_01SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preB2_02(preB2_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preB2_03(preB2_03SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Kxpp(KxppSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Kypp(KyppSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Kpp(KppSEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_stiffness(k, ML, detB, vals, nele, xPos, coef, Bj, C, node_x, node_y, el_1, pre11_01, pre11_02, pre11_03, pre11_AC, pre22_01, pre22_02, pre22_03, pre22_BC, preB1_01, preB1_02, preB1_03, preB2_01, preB2_02, preB2_03, Kxpp, Kypp, Kpp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Jsmm_assemble_coefs", (DL_FUNC) &_Jsmm_assemble_coefs, 14},
    {"_Jsmm_assemble_integral", (DL_FUNC) &_Jsmm_assemble_integral, 6},
    {"_Jsmm_assemble_mass", (DL_FUNC) &_Jsmm_assemble_mass, 6},
    {"_Jsmm_assemble_stiffness", (DL_FUNC) &_Jsmm_assemble_stiffness, 29},
    {NULL, NULL, 0}
};

RcppExport void R_init_Jsmm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
