# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assemble_coefs <- function(pqx, rqx, pqy, rqy, C, method, XBeta_diffusion, XBeta_advection_1, XBeta_advection_2, XBeta_mortality, nele, node_x, node_y, el_1) {
    .Call(`_Jsmm_assemble_coefs`, pqx, rqx, pqy, rqy, C, method, XBeta_diffusion, XBeta_advection_1, XBeta_advection_2, XBeta_mortality, nele, node_x, node_y, el_1)
}

assemble_integral <- function(k_v, detB, nnod, ns, nele, el_v) {
    .Call(`_Jsmm_assemble_integral`, k_v, detB, nnod, ns, nele, el_v)
}

assemble_mass <- function(k, ML, detB, vals, nele, xPos) {
    .Call(`_Jsmm_assemble_mass`, k, ML, detB, vals, nele, xPos)
}

assemble_stiffness <- function(k, ML, detB, vals, nele, xPos, coef, Bj, C, node_x, node_y, el_1, pre11_01, pre11_02, pre11_03, pre11_AC, pre22_01, pre22_02, pre22_03, pre22_BC, preB1_01, preB1_02, preB1_03, preB2_01, preB2_02, preB2_03, Kxpp, Kypp, Kpp) {
    .Call(`_Jsmm_assemble_stiffness`, k, ML, detB, vals, nele, xPos, coef, Bj, C, node_x, node_y, el_1, pre11_01, pre11_02, pre11_03, pre11_AC, pre22_01, pre22_02, pre22_03, pre22_BC, preB1_01, preB1_02, preB1_03, preB2_01, preB2_02, preB2_03, Kxpp, Kypp, Kpp)
}

